<a href="https://colab.research.google.com/github/lenaphamthi/MachineLearning/blob/main/Chuong1_KienThucCoBan/vector_ma_tran_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Cho v là 1 vector hàng 
v= [1, 2, 3, 4, 5]

Lưu ý: vector tương ứng với tensor hạng 1



In [ ]:
import numpy as np 
v = np.array([1, 2, 3,4,5])

2. Cho w là 1 vcetor cột
w= [1;2;3;4;5]

Lưu ý: vector cũng có thể biểu diễn như là tensor hạng 2 ở trường hợp đặc biệt là $\mathrm{R}^{m*1}$




In [ ]:
w = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)

3. Hãy xác định số chiều (ndim), kích thước (shape) của 2 vector v và w; 
In 2 vector v và w ra màn hình; Nhận xét điểm khác biệt của kết quả)


In [ ]:
#số chiều (ndim) cua vector v 
v.ndim

1

In [ ]:
##số chiều (ndim) cua vector w 
w.ndim

2

In [ ]:
#kích thước (shape) cua vector v 
v.shape

(5,)

In [ ]:
##kích thước (shape) cua vector w 
w.shape

(5, 1)

*Nhận xét: **v** là một vector (tensor hạng 1) , **w**  là ma trận (tensor hạng 2)*

4. Cho u và w là 2 vector cột có kích thước (m, 1). Hãy tạo ma trận X bằng cách ghép 2 vector cột u và w lại với nhau
X= [u, w]
*   Cách 1: sử dụng hàm np.column_stack()
*   Cách 2:sử dụng hàm np.hstack()

Hãy xác định số chiều, kích thước và in nội dung ma trận X ra màn hình




In [ ]:
np.random.seed(0)
u = np.random.randint(low = 0, high = 20, size = (5, 1)) 
w = np.random.randint(low = 0, high = 20, size = (5, 1))

In [ ]:
print(u) 

[[12]
 [15]
 [ 0]
 [ 3]
 [ 3]]


In [ ]:
print(w)

[[ 7]
 [ 9]
 [19]
 [18]
 [ 4]]


In [ ]:
#Tạo ma trận X bằng cách ghép 2 vector cột u và w 
#Cách 1: sử dụng hàm np.column_stack()


In [ ]:
#Sô chiều của X:


2

In [ ]:
#KKích thước của X:


(5, 2)

In [ ]:
#In ma trận X
X

array([[12,  7],
       [15,  9],
       [ 0, 19],
       [ 3, 18],
       [ 3,  4]])

5. Hãy tạo ma trận X có giá trị như sau
X= [1 6 4  2 7 5  3 8 7  4 9 2  5 2 1 ]   
*   Hãy tạo ma trận X bằng np.array()
*  Hãy tạo ma trận X bằng hàm np.reshape()
*  Hãy xác định số chiều, kích thước và in nội dung ma trận X ra màn hình


In [ ]:
X = np.array([
    [1, 6, 4, 2, 7],
    [5, 3, 8, 7, 4],
    [9, 2, 5, 2, 1]])

In [ ]:
#Tạo ma trận X bằng hàm np.reshape()
X = np.array([1,6,4,2,7,5,3,8,7, 4,9,2, 5,2,1]).reshape(3,5)

In [ ]:
#Số chiều X: 
X.ndim

2

In [ ]:
#Kích thước X :
X.shape

(3, 5)

In [ ]:
#In ma trận X 
X

array([[1, 6, 4, 2, 7],
       [5, 3, 8, 7, 4],
       [9, 2, 5, 2, 1]])

6. Hãy nhân ma trận X với vector v
*   Sử dụng hàm np.dot()
*   Xác định chiều, kích thước và in nội dung kết quả phép nhân ra màn hình


In [ ]:
#hàm np.dot() để nhân ma trận X với vector v 
mt1 = np.dot(X, v)

In [ ]:
#Chiều của phép nhân 
mt1.ndim

1

In [ ]:
#kích thước 
mt1.shape

(3,)

In [ ]:
#in kết quả 
mt1

array([68, 83, 41])

7. Hãy nhân ma trận X với vector w
*   Sử dụng hàm np.dot()
*   Xác định chiều, kích thước và in nội dung kết quả phép nhân ra màn hình


In [ ]:
#hàm np.dot() để nhân ma trận X với vector w 
mt2 = np.dot(X, w)

In [ ]:
#chiều của phép nhân 
mt2.ndim

2

In [ ]:
#kích thước 
mt2.shape 

(3, 1)

In [ ]:
#in kết quả 
mt2

array([[201],
       [356],
       [216]])

*Khác biệt giữa kết quả câu 6 và 7 là về chiều và kích thước (tensor)*


8. Xét ma trận X ở câu 5, hãy tìm ma trận chuyển vị của X, ký hiệu là XT
*   Hãy sử dụng cú pháp .T của gói numpy để tìm ma trận chuyển vị.





In [ ]:
X.T

array([[1, 5, 9],
       [6, 3, 2],
       [4, 8, 5],
       [2, 7, 2],
       [7, 4, 1]])